# Cognitive Service integration using SDK 
# Documentation: https://learn.microsoft.com/en-us/azure/ai-services/computer-vision/quickstarts-sdk/image-analysis-client-library-40

# @title Variables
@API_VISION_URL= {{API_URL}}/vision

#########################################################
# @title Analyze an image to get features: Text, Objects, Tags
POST {{API_VISION_URL}}/analyze?imageurl=https://i.stack.imgur.com/WiDpa.jpg
Content-Type: application/json



